### ISSUE TITLE
Q. How about workflow?

### ISSUE THREAD

**Issue by webiroha** [chingu-voyages/v17-chimeras-team-01#6]
### 1. Code Style Guide
**Which style guide do you want to use?**
• Airbnb JavaScript Style Guide
• Google JavaScript Style Guide
• Idiomatic JavaScript Style Guide
• JavaScript Standard Style Guide
and / or 
• use a VSCode extension like ESLint or Prettier to format

**[Answer]**
Jo:
Jinyoung:
Keiko: up to you(if not have any idea, might be good to use Airbnb and VSCode extensions)

### 2. Git Strategy
**Is it OK to use the Git workflows presented by them?**
https://docs.chingu.io/techres/gitworkflow
**Or do you want to use anything else like "GitHub flow"?**

**[Answer]**
Jo:
Jinyoung:
Keiko: up to you (I think following the page is good)

### 3. Code Merge Process
**• Will you be using GitHub's Pull Request?**
**[Answer]**
Jo:
Jinyoung:
Keiko: hopefully, but whichever

**• Will you pull the destination branch into your branch first?** 
**Or just attempt to merge straight in?**
**[Answer]**
Jo:
Jinyoung:
Keiko: not sure, might be better to pull the destination branch?

**• Will there be a mandatory code review by one other person before merging?**
**[Answer]**
Jo:
Jinyoung:
Keiko: hopefully, want to do it.

**• What happens if there are merge conflicts?**
**[Answer]**
Jo:
Jinyoung:
Keiko: consulting to someone is good?

**• Can the Pull Request be merged by anyone? Or just the Project Manager? Or only by the person in charge of that code section?**
**[Answer]**
Jo:
Jinyoung:
Keiko: whoever. anyone is better for me.

### reference:
https://docs.chingu.io/voyage/project/workflow#3-code-merge-process

**Comment by jypark0407** [comment]
1. Code Style Guide

Which style guide do you want to use?
• Airbnb JavaScript Style Guide
• Google JavaScript Style Guide
• Idiomatic JavaScript Style Guide
• JavaScript Standard Style Guide
and / or
• use a VSCode extension like ESLint or Prettier to format

[Answer]
Jo:
Jinyoung:I'd prefer to use JavaScript Standard Style Guide as it does not require ESLint and comes with automation.
Keiko: up to you(if not have any idea, might be good to use Airbnb and VSCode extensions)
2. Git Strategy

Is it OK to use the Git workflows presented by them?
https://docs.chingu.io/techres/gitworkflow
Or do you want to use anything else like "GitHub flow"?

[Answer]
Jo:
Jinyoung:I think it'll be great to follow the recommendation on the Chingu page. It seems similar to the development process used by the developers. 
Keiko: up to you (I think following the page is good)
3. Code Merge Process

• Will you be using GitHub's Pull Request?
[Answer]
Jo:
Jinyoung:I'll be using it as I'll be primarly working in a local environment instead of directly writing code on GitHub. 
Keiko: hopefully, but whichever

• Will you pull the destination branch into your branch first?
Or just attempt to merge straight in?
[Answer]
Jo:
Jinyoung:Not sure about this, probably I don't fully understand the question...
Keiko: not sure, might be better to pull the destination branch?

• Will there be a mandatory code review by one other person before merging?
[Answer]
Jo:
Jinyoung:I think the code review is important. If there are any conflicts, we'll have to do it anyway.
Keiko: hopefully, want to do it.

• What happens if there are merge conflicts?
[Answer]
Jo:
Jinyoung:We'll need to identify a team member who also wrote the code and consult with that person about the conflict.
Keiko: consulting to someone is good?

• Can the Pull Request be merged by anyone? Or just the Project Manager? Or only by the person in charge of that code section?
[Answer]
Jo:
Jinyoung:I think the preson in charge of the code section should merge the pull request as it will make things more clear and simple.
Keiko: whoever. anyone is better for me.

**Comment by webiroha** [comment]
>• Will you pull the destination branch into your branch first?
Or just attempt to merge straight in?

I am also unsure this.
Might it be OK to ignore?
I caught these questions from the Chingu Handbook.

**Comment by webiroha** [comment]
>• Will you pull the destination branch into your branch first?
Or just attempt to merge straight in?

I tried to ask them about this.
It meant we only have the first option.

> when you're working on a branch of a repo, you are working on a copy of the original code. Once you've made a change you need to merge that code to the original for it to become part of the codebase.
> The first option is to check and see if there are any changes to the branch you're wanting to add your code to. That's called "pulling" the destination branch into your branch. That's a good way for you to make sure you have any updates that have been made to the code since you created your copy of it to work on. If there are changes, you then can work to make sure your code isn't conflicting with any of those changes before you "push" your code up.
> You are also able to avoid erasing anybody else's work that they've merged!
> The second option is just to merge your code without pulling the original in. This should really only be the process if you are the sole person working on that code as it will just immediately update the original so that your changes are Incorporated.

**Comment by jmoralesg** [comment]
Code Style Guide
Which style guide do you want to use?
• Airbnb JavaScript Style Guide
• Google JavaScript Style Guide
• Idiomatic JavaScript Style Guide
• JavaScript Standard Style Guide
and / or
• use a VSCode extension like ESLint or Prettier to format

[Answer]
Jo: Wow this is the first time I am faced with this question, I usually use ESLint, and it would be great to learn to use the JavaScript Standard Style Guide for a change 
Jinyoung:I'd prefer to use JavaScript Standard Style Guide as it does not require ESLint and comes with automation.
Keiko: up to you(if not have any idea, might be good to use Airbnb and VSCode extensions)
2. Git Strategy

Is it OK to use the Git workflows presented by them?
https://docs.chingu.io/techres/gitworkflow
Or do you want to use anything else like "GitHub flow"?

[Answer]
Jo: What is presented is good, I wouldn't know other way of doing it
Jinyoung:I think it'll be great to follow the recommendation on the Chingu page. It seems similar to the development process used by the developers.
Keiko: up to you (I think following the page is good)
3. Code Merge Process

• Will you be using GitHub's Pull Request?
[Answer]
Jo: I will 
Jinyoung:I'll be using it as I'll be primarly working in a local environment instead of directly writing code on GitHub.
Keiko: hopefully, but whichever

• Will you pull the destination branch into your branch first?
Or just attempt to merge straight in?
[Answer]
Jo: The question is a bit confusing but what I understand is it refers to pulling code before adding your code, so I will always pull the destination branch so before I merge my code I have all the changes made to the destination branch and so that will avoid merge conflicts. 
Jinyoung:Not sure about this, probably I don't fully understand the question...
Keiko: not sure, might be better to pull the destination branch?

• Will there be a mandatory code review by one other person before merging?
[Answer]
Jo: code reviewing would be great practice
Jinyoung:I think the code review is important. If there are any conflicts, we'll have to do it anyway.
Keiko: hopefully, want to do it.

• What happens if there are merge conflicts?
[Answer]
Jo: as Jynyoung says, communicate with the team and resolve the conflict 
Jinyoung:We'll need to identify a team member who also wrote the code and consult with that person about the conflict.
Keiko: consulting to someone is good?

• Can the Pull Request be merged by anyone? Or just the Project Manager? Or only by the person in charge of that code section?
[Answer]
Jo: since we will be doing code reviews, the person in charge of the section can merge the pull request 
Jinyoung:I think the preson in charge of the code section should merge the pull request as it will make things more clear and simple.
Keiko: whoever. anyone is better for me.

**Comment by webiroha** [comment]
Latest:
1. Code Style Guide

Which style guide do you want to use?
• Airbnb JavaScript Style Guide
• Google JavaScript Style Guide
• Idiomatic JavaScript Style Guide
• JavaScript Standard Style Guide
and / or
• use a VSCode extension like ESLint or Prettier to format

[Answer]
Jo:
Jinyoung:I'd prefer to use JavaScript Standard Style Guide as it does not require ESLint and comes with automation.
Keiko: up to you(if not have any idea, might be good to use Airbnb and VSCode extensions)
2. Git Strategy

Is it OK to use the Git workflows presented by them?
https://docs.chingu.io/techres/gitworkflow
Or do you want to use anything else like "GitHub flow"?

[Answer]
Jo:
Jinyoung:I think it'll be great to follow the recommendation on the Chingu page. It seems similar to the development process used by the developers. 
Keiko: up to you (I think following the page is good)
3. Code Merge Process

• Will you be using GitHub's Pull Request?
[Answer]
Jo:
Jinyoung:I'll be using it as I'll be primarly working in a local environment instead of directly writing code on GitHub. 
Keiko: hopefully, but whichever

• Will there be a mandatory code review by one other person before merging?
[Answer]
Jo:
Jinyoung:I think the code review is important. If there are any conflicts, we'll have to do it anyway.
Keiko: hopefully, want to do it.

• What happens if there are merge conflicts?
[Answer]
Jo:
Jinyoung:We'll need to identify a team member who also wrote the code and consult with that person about the conflict.
Keiko: consulting to someone is good?

• Can the Pull Request be merged by anyone? Or just the Project Manager? Or only by the person in charge of that code section?
[Answer]
Jo:
Jinyoung:I think the preson in charge of the code section should merge the pull request as it will make things more clear and simple.
Keiko: whoever. anyone is better for me.
